### ISSUE TITLE
FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by JianfeiMa** [danielgatis/rembg#668]
2024-09-07 14:23:35.189200391 [E:onnxruntime:Default, provider_bridge_ort.cc:1978 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1637 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libcublas.so.12: cannot open shared object file: No such file or directory

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:490 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(PySessionOptions&, const onnxruntime::ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-09-07 14:23:35.282705908 [E:onnxruntime:Default, provider_bridge_ort.cc:1992 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1637 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.12: cannot open shared object file: No such file or directory

**Comment by evan00144** [comment]
any updataes onm this?

**Comment by Karsten-Larson** [comment]
I am experiencing the same issue

**Comment by Grizemc** [comment]
Maybe onnxtime has download problem

**Comment by Quantuman134** [comment]
I install a previous version released in 2023, and worked out

**Comment by AD1PRAJAPATI** [comment]
try  below steps  

-> onnxruntime-gpu version ==1.19.2
-> torch version ==2.4.1 
-> CUDA VERSION > 12(based on the error you would be having greater than 12 ) 
-> cuDNN VERISON > 9(just check this if you have cuDNN version 8.9 then you would be requiring 
torch version 2.3.1  and  onnxruntime-gpu version 1.18.0
)

-> after installing this you would get error like FAILED to find `libcudnn_cnn.so.9` so for that youll need to export lib path of that and run the command like this 

`LD_LIBRARY_PATH=$LD_LIBRARY_PATH: /miniconda3/envs/{your_enviroment}/lib/python3.11/site-packages/nvidia/cudnn/lib CUDA_VISIBLE_DEVICES=7 python {your_pythonscript}.py `

-> also before running the above  just pass the provider in the session eg: `session = new_session("{model_name}",providers=['CUDAExecutionProvider'])` (you can check what providers you have using `import onnxruntime as ort `
` print(ort.get_available_providers())`)

-> The above steps worked for me , Thank you

**Comment by catscarlet** [comment]
Here is the final result what I tried for months.


part of my dockerfile
```
FROM nvidia/cuda:12.2.2-devel-ubuntu22.04

RUN apt update
RUN apt install -y --no-install-recommends python3-pip
RUN pip install onnxruntime-gpu --break-system-packages
RUN pip install "rembg[gpu,cli]" --break-system-packages
```

I use cuda:12.2 because my host only support cuda:12.2 right now.

And when I ran rembg, this happened:

```
2025-02-20 13:39:39.615359815 [E:onnxruntime:Default, provider_bridge_ort.cc:1848 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:507 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(PySessionOptions&, const onnxruntime::ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2025-02-20 13:39:39.740567077 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory
```

I think most of the issues, in this repository are related to the **onnxruntime can't find cuda and tensorrt** issue, which wasn't there before. The inactive auto-closed just hide them like they were solved.
(The default Dockerfile is repository even has `RUN python -m pip install ".[cpu,cli]"` which are already funny)

I also tried to use different onnxruntime version and whatever. I don't remember which was the last one that worked.
The requirement of **the whole thing of cuda** is already hilarious, and it also require **TensorRT**, which you can't even install it without **a complex nvidia developer sign up**, which I couldn't get one.

I say Microsoft fucks up all onnxruntime users.

It's dead. All open source onnx remove backgournd tools are dead. There are only commercial image editors with rembg features.
Just suffer with CPU when using it.

**Comment by AD1PRAJAPATI** [comment]
I totally get it—this whole ONNXRuntime + CUDA + TensorRT setup is a mess. You're definitely not the only one dealing with this headache.

From what you’ve shared, it’s still failing because TensorRT ```(libnvinfer.so.10)``` isn’t installed and cuDNN ```(libcudnn.so.9)``` isn’t being found. I actually mentioned the LD_LIBRARY_PATH fix in my last response, so you might wanna try that.

For TensorRT, if you don’t really need it, just use ```new_session("{model_name}",providers=['CUDAExecutionProvider'])``` when setting up the session. That way, it won’t even try to load TensorRT and fail.

Honestly, the way ONNXRuntime handles dependencies is kinda trash, but it’s not completely dead yet. If you still wanna troubleshoot, I’m happy to try!

**Comment by catscarlet** [comment]
@AD1PRAJAPATI Thanks for your reply.

> From what you’ve shared, it’s still failing because TensorRT `(libnvinfer.so.10)` isn’t installed and cuDNN `(libcudnn.so.9)` isn’t being found. I actually mentioned the LD_LIBRARY_PATH fix in my last response, so you might wanna try that.

Well funny things:
- **nvidia/cuda:12.2.2-devel-ubuntu22.04** doesn't include file **libcudnn.so.9**
- As my search on dockerhub, **cuda:12.2** version only has **12.2.2-cudnn8**, which includes **libcudnn.so.8**, not **libcudnn.so.9**

My host right now is using ubuntu 20.04 based system so it only has old driver which only supports cuda 12.2. (yes i know it's coming  eol. i just don't have time to upgrade it).

Well. I think this is the best I can do.

**Comment by catscarlet** [comment]
> Yo, real quick—what versions of torch and torchvision are you running? Just wanna see if they line up with your CUDA/cuDNN setup, ‘cause that might be causing some of this chaos. Wouldn't be surprised if a mismatch is messing things up.

Funny thing: I didn't manually install pytorch. I think there is no pytorch in my docker image.

**Comment by catscarlet** [comment]
So I made a **Great Breakthrough**

Here is the core of the Dockerfile I build for testing

```
FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

RUN apt update
RUN apt install -y --no-install-recommends python3-pip
RUN pip install onnxruntime-gpu --break-system-packages
RUN pip install "rembg[gpu,cli]" --break-system-packages
```

Command I used for running docker:
`docker run --gpus all -v /dev/dri:/dev/dri -v /mystorage2/libs/u2net:/root/.u2net -v $PWD:/rembg rembg-docker-gpu-test`

Yea I upgrade my computer to Linux Mint 22.1 (based on Ubuntu24.04) so now my driver is 550.120 with CUDA 12.4

The onnxruntime-gpu version in this test is confirmed **1.20.1** by `print(onnxruntime.__version__)`

```
:~$ nvidia-smi
Fri Feb 28 13:41:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4     |
```

After the docker image build finish. I test and it doesn't have the lib missing issue anymore, **BUT it still use ONLY CPU** .

Then I run some debug and here is the big deal.

In rembg/sessions/base.py, i add both `print(ort.get_device())` and `print(ort.get_available_providers())` in *__init__* and it gives this everytime I run it.

```
GPU
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
```

So now I'm sure two thing, 
- onnxruntime-gpu was successfully installed and it can detect GPU
- It says TensorrtExecutionProvider is one of the available provider, which was totally wrong because I didn't install any of Tensorrt shit.


I continued my testing and this made a great progress:

```
def __init__(self, model_name: str, sess_opts: ort.SessionOptions, providers=['CUDAExecutionProvider'], *args, **kwargs):
        """Initialize an instance of the BaseSession class."""
        self.model_name = model_name
        #providers = ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']     //Ignore this.
        providers = ['CUDAExecutionProvider']       //This
        self.inner_session = ort.InferenceSession(
            str(self.__class__.download_models(*args, **kwargs)),
            sess_options=sess_opts,
            providers=providers,                                   //And this
        )
```

Now I'm forcing onnxruntime to using CUDAExecutionProvider, and it worked. I can hear the fan of Graphic Card instead of CPU's

The speed difference between with and with out `providers = ['CUDAExecutionProvider']` when running `time rembg i -m birefnet-general realesrgan2x.png realesrgan2x_rembg.png `

With `providers = ['CUDAExecutionProvider']` 
```

GPU
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

real	0m11.130s
user	0m10.317s
sys	0m1.438s
```

Without `providers = ['CUDAExecutionProvider']` 
```
root@003e1933d74c:/rembg# time rembg i -m birefnet-general realesrgan2x.png realesrgan2x_rembg.png 
GPU
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

real	0m29.869s
user	1m9.945s
sys	0m3.733s

```



Now I'm sure **this is a terrible onnxruntime bug** . In common sense, it usually goes like this:
- Use an onnxruntime.get_available_providers() order like `['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']`
- Try using GPU, if fail, try CPU as failsafe. (it's actually as same as the above one)

Turns out by default onnxruntime/onnxruntime-gpu use CPU at first with no reason. WTF!
Yeah if I try `providers = ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']`, which the TensorrtExecutionProvider would break, it still go like this:
```
2025-02-28 13:58:36.158909947 [E:onnxruntime:Default, provider_bridge_ort.cc:1848 TryGetProviderInfo_TensorRT] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_tensorrt.so with error: libnvinfer.so.10: cannot open shared object file: No such file or directory

*************** EP Error ***************
EP Error /onnxruntime_src/onnxruntime/python/onnxruntime_pybind_state.cc:507 void onnxruntime::python::RegisterTensorRTPluginsAsCustomOps(PySessionOptions&, const onnxruntime::ProviderOptions&) Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
GPU
['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']

real	0m10.730s
user	0m10.174s
sys	0m1.472s
```

Yeah after TensorRT fail, it goes CUDA for accurately.

So I think this one is related to many issues like: #682 #664 #707 #439 #696


Conclusion:
Onnxruntime messed us up. Onnxruntime requires terrible cuda and cudnn compatibility. Provider must be provided to onnxruntime or it will use CPU first even we install onnxruntime-gpu.

Fix:
I'm still now very sure. The official dockerfile declared `FROM python:3.10-slim` and `RUN python -m pip install ".[cpu,cli]"`. I don't know if we can run rembg[gpu] without cuda nor cuddn nor onnxruntime-gpu.
Maybe more tests is needed.

**Comment by catscarlet** [comment]
> I'm still now very sure. The official dockerfile declared `FROM python:3.10-slim` and `RUN python -m pip install ".[cpu,cli]"`. I don't know if we can run rembg[gpu] without cuda nor cuddn nor onnxruntime-gpu.
> Maybe more tests is needed.

OK CUDA is still needed. onnxruntime is installed by `setup.py`.

**Comment by AD1PRAJAPATI** [comment]
Damn, that’s wild. So ONNXRuntime really just defaulting to CPU even when GPU is available? That’s actually insane. Makes no sense why it wouldn’t prioritize CUDAExecutionProvider automatically.

The whole TensorrtExecutionProvider thing is hilarious too—like, bro, I didn’t even install TensorRT, why are you acting like it’s there? 😂

Lowkey feels like ONNXRuntime just doesn’t know what to do unless you explicitly tell it to use CUDA. Also, the fact that it still falls back properly after TensorRT fails but won’t just go straight to CUDA first?? Yeah, that’s sus.

Appreciate you digging into this though, ‘cause this might be the reason so many people are struggling with ONNX and GPUs. I’m guessing the only real fix (for now) is to force CUDAExecutionProvider in the code. But man, ONNXRuntime gotta get it together.

**Comment by catscarlet** [comment]
> The whole TensorrtExecutionProvider thing is hilarious too—like, bro, I didn’t even install TensorRT, why are you acting like it’s there?

I got funnier one. I tried **nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04** to replace **nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04** so to save disk space, but cudnn-runtime gives me this:
```
root@1ab131f73295:/rembg# rembg i -m birefnet-general 20250224182548.png 20250224182548_rembg2.png 
Segmentation fault (core dumped)
```

So **cudnn-devel** is required.
I also tried plain cuda but libcudnn is required and cuda doesn't offer libcudnn
```
root@7cec443ec049:/rembg# rembg i -m birefnet-general 20250224182548.png 20250224182548_rembg.png 
2025-02-28 14:56:30.568092315 [E:onnxruntime:Default, provider_bridge_ort.cc:1862 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1539 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory

root@7cec443ec049:/rembg# find / -name libcudnn*
root@7cec443ec049:/rembg# 
```

What a shitty show.

**Comment by kzhang2** [comment]
To fix this issue, I believe we can use my solution posted in a different thread to properly enable `Tensorrt` support for `rembg`: https://github.com/danielgatis/rembg/issues/707#issuecomment-2855062603. I'd also like to point out to @catscarlet that the `Tensorrt` libraries can be installed through `pip` without registering for an NVIDIA developer account, and my comment shows how to do so.
