### ISSUE TITLE
[BUG] Defaults To CPU even though GPUExecutionProvider is mentioned

### ISSUE THREAD

**Issue by theandreibogdan** [danielgatis/rembg#744]
**Describe the bug**
I get this warning/error:
```
2025-03-19 20:08:22.213835911 [E:onnxruntime:Default, provider_bridge_ort.cc:2036 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1695 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcublasLt.so.12: cannot open shared object file: No such file or directory
```

**To Reproduce**
It gives me the warning when it gets to this code:
```
# Create rembg session with specified model
    logging.info("Creating rembg session with model 'birefnet-hrsod'.")
    session = rembg.new_session(model_name="birefnet-hrsod", providers=["CUDAExecutionProvider","CPUExecutionProvider"])
    logging.info("Rembg session created successfully.")
```
My environment is:
- Debian Slim
- Python 3.12
- onnxruntime-gpu, rembg[gpu], pillow

I am trying to run it in a Modal.com container and most probably works exactly like a docker container and they say CUDA is installed by default

**Rembg version:**
v2.0.21

It works, but acts as if the GPU is not even there and defaults to CPU, I guess

I can't tell exactly what is going on. (I am pretty new to all this stuff)

**Comment by Firdavs-coder** [comment]
The same error for me

**Comment by catscarlet** [comment]
Probably related to this https://github.com/danielgatis/rembg/issues/668#issuecomment-2689914205
CUDA is not enough for this because onnxruntime-gpu messed up. **cuda-cudnn-devel** is required.

If you are going to use rembg[gpu] in docker you need to build the image by yourself.

Try the **Nvidia CUDA Hardware Acceleration** part <https://github.com/danielgatis/rembg?tab=readme-ov-file#nvidia-cuda-hardware-acceleration> in Readme.md .

**Comment by MorrowxD** [comment]
Same issue with dockered rembg onnxruntime and rocm/amd, any tips how to set it up?

**Comment by Firdavs-coder** [comment]
> Same issue with dockered rembg onnxruntime and rocm/amd, any tips how to set it up?

Yesterday, I tried this and it worked...

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb
sudo apt-get update
sudo apt-get -y install cudnn

sudo apt-get -y install cudnn-cuda-12
```
