### ISSUE TITLE
error: libcudnn.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by onlineapps-cloud** [danielgatis/rembg#798]
hi, i just tried your great tool on ubuntu 24, when i run software i get this error:
```
./rembg p /home/ubuntu/images /home/ubuntu/
Downloading data from 'https://github.com/danielgatis/rembg/releases/download/v0.0.0/u2net.onnx' to file '/home/ubuntu/.u2net/u2net.onnx'.
100%|███████████████████████████████████████| 176M/176M [00:00<00:00, 1.43TB/s]
2025-10-30 11:03:17.233410897 [E:onnxruntime:Default, provider_bridge_ort.cc:2251 TryGetProviderInfo_CUDA] /onnxruntime_src/onnxruntime/core/session/provider_bridge_ort.cc:1844 onnxruntime::Provider& onnxruntime::ProviderLibrary::Get() [ONNXRuntimeError] : 1 : FAIL : Failed to load library libonnxruntime_providers_cuda.so with error: libcudnn.so.9: cannot open shared object file: No such file or directory

100%|██████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.84it/s]
```

but background for image was removed! i installed onnxruntime-gpu  wihtout errors, i don't know why this error appear, if you need additional logs for debug problem, let me know, best regards.

**Comment by onlineapps-cloud** [comment]
problem was solved by installing additional components:

```
# Download and install NVIDIA's repository key
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
sudo dpkg -i cuda-keyring_1.1-1_all.deb

# Update package list
sudo apt-get update

# Install CUDNN
sudo apt-get install libcudnn9-cuda-12 libcudnn9-dev-cuda-12
```
